### ISSUE TITLE
FAQ: Broken link to download fonts

### ISSUE THREAD

**Issue by onebree** [wps-community/wps_community_website#39]
- Page: http://wps-community.org/faq
- Broken link: http://wps-community.org/download/fonts
- Error: "Page Not Found"

Where can I download the fonts mentioned in the FAQ?

**Comment by jinchizhong** [comment]
Hi friend.

For some reason.
We have removed all copyleft fonts in our website.
You need to find it elsewhere.

Sorry

**Comment by onebree** [comment]
Thank you. Will the FAQs be updated to reflect this? And, what were the copyleft fonts you used to provide?

**Comment by AusNugz** [comment]
#40 solves this.

**Comment by AusNugz** [comment]
@jinchizhong can this issue be closed?

**Comment by onebree** [comment]
Closed with #40
